import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { createDeck, deleteDeck, getDeck, listDecks, summary, updateDeck } from '../controllers/deck.controller.js';
import { exportPptx, listExports } from '../controllers/export.controller.js';
import { generateDeckOutline, generateDeckSlides, getOutline, updateOutline } from '../controllers/outline.controller.js';
import { createSlide, listSlides, reorderSlides } from '../controllers/slide.controller.js';
import { authMiddleware } from '../middleware/authMiddleware.js';
import { validateBody } from '../middleware/validateRequest.js';
import { validateCreateDeck, validateOutline, validateReorder, validateSlide } from '../validators/common.js';
import { asyncHandler } from '../utils/asyncHandler.js';
const router = Router();
const aiLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 30 });
router.use(authMiddleware);
router.get('/', asyncHandler(listDecks));
router.get('/stats/summary', asyncHandler(summary));
router.post('/', validateBody(validateCreateDeck), asyncHandler(createDeck));
router.get('/:deckId', asyncHandler(getDeck));
router.patch('/:deckId', asyncHandler(updateDeck));
router.delete('/:deckId', asyncHandler(deleteDeck));
router.post('/:deckId/outline/generate', aiLimit, asyncHandler(generateDeckOutline));
router.get('/:deckId/outline', asyncHandler(getOutline));
router.put('/:deckId/outline', validateBody(validateOutline), asyncHandler(updateOutline));
router.post('/:deckId/slides/generate', aiLimit, asyncHandler(generateDeckSlides));
router.get('/:deckId/slides', asyncHandler(listSlides));
router.post('/:deckId/slides', validateBody(validateSlide), asyncHandler(createSlide));
router.patch('/:deckId/slides/reorder', validateBody(validateReorder), asyncHandler(reorderSlides));
router.post('/:deckId/export/pptx', asyncHandler(exportPptx));
router.get('/:deckId/exports', asyncHandler(listExports));
export default router;
